description: Standardized Moorings Layout using Jensen-Jimenez
farm:
  layout_x:
  - 9260.909017761205
  - 7830.96817776143
  - 6401.027337761652
  - 4971.086497761877
  - 3541.1456577621
  - 2111.204817762324
  - 681.2639777625479
  - -748.6768622372283
  - -2178.6177022370043
  - -3608.558542236781
  - -5038.499382236558
  - -6468.440222236333
  - -7898.381062236111
  - -9328.321902235886
  - 8647.357813320627
  - 7217.41697332085
  - 5787.476133321074
  - 4357.535293321298
  - 2927.5944533215215
  - 1497.653613321745
  - 67.71277332196883
  - -1362.2280666778074
  - -2792.1689066775834
  - -4222.10974667736
  - -5652.050586677136
  - -7081.991426676912
  - -8511.93226667669
  - 9463.747448879823
  - 8033.806608880048
  - 6603.865768880271
  - 5173.924928880495
  - 3743.9840888807184
  - 2314.0432488809424
  - 884.1024088811662
  - -1975.7792711183863
  - -3405.720111118162
  - -4835.660951117939
  - -6265.601791117715
  - -7695.542631117491
  - -9125.483471117268
  - 8850.196244439245
  - 7420.255404439468
  - 5990.314564439692
  - 4560.373724439915
  - 3130.43288444014
  - 1700.4920444403633
  - 270.5512044405872
  - -1159.3896355591892
  - -2589.330475558965
  - -4019.271315558741
  - -5449.212155558518
  - -6879.152995558295
  - -8309.09383555807
  - 8236.645039998664
  - 6806.70419999889
  - 5376.763359999113
  - 3946.8225199993367
  - 2516.8816799995607
  - 1086.9408399997844
  - -342.99999999999187
  - -1772.940839999768
  - -3202.8816799995443
  - -4632.82251999932
  - -6062.763359999097
  - -7492.704199998873
  - -8922.64503999865
  - 9053.034675557863
  - 7623.093835558086
  - 6193.15299555831
  - 4763.2121555585345
  - 3333.2713155587576
  - 1903.3304755589816
  - 473.3896355592053
  - -956.5512044405709
  - -2386.492044440347
  - -3816.4328844401234
  - -5246.3737244399
  - -6676.314564439675
  - -8106.255404439453
  - 8439.483471117284
  - 7009.542631117507
  - 5579.601791117731
  - 4149.660951117955
  - 2719.7201111181785
  - 1289.7792711184027
  - -140.16156888137357
  - -1570.1024088811498
  - -3000.043248880926
  - -4429.984088880702
  - -5859.924928880479
  - -7289.865768880255
  - -8719.806608880031
  - 9255.873106676481
  - 7825.932266676706
  - 6395.991426676928
  - 4966.050586677153
  - 3536.1097466773763
  - 2106.1689066776
  - -753.7127733219527
  - -2183.6536133217287
  - -3613.594453321505
  - -5043.535293321282
  - -6473.476133321057
  - -7903.416973320834
  - -9333.35781332061
  - 8642.321902235903
  - 7212.381062236127
  - 5782.44022223635
  - 4352.499382236574
  - 2922.558542236798
  - 1492.6177022370216
  - 62.67686223724559
  - -1367.2639777625307
  - -2797.204817762307
  - -4227.145657762083
  - -5657.086497761859
  - -7087.027337761636
  - -8516.968177761411
  - 9458.711537795098
  - 8028.770697795324
  - 6598.8298577955475
  - 5168.88901779577
  - 3738.9481777959945
  - 2309.007337796218
  - 879.0664977964416
  - -550.8743422033344
  - -1980.8151822031107
  - -3410.756022202887
  - -4840.696862202663
  - -6270.637702202439
  - -7700.578542202215
  - -9130.519382201992
  layout_y:
  - 11811.817836166982
  - 11811.818634796608
  - 11811.819433426232
  - 11811.820232055856
  - 11811.821030685482
  - 11811.821829315106
  - 11811.82262794473
  - 11811.823426574356
  - 11811.82422520398
  - 11811.825023833604
  - 11811.82582246323
  - 11811.826621092854
  - 11811.827419722478
  - 11811.828218352104
  - 9164.112378838206
  - 9164.113177467832
  - 9164.113976097457
  - 9164.11477472708
  - 9164.115573356707
  - 9164.11637198633
  - 9164.117170615955
  - 9164.11796924558
  - 9164.118767875205
  - 9164.119566504829
  - 9164.120365134455
  - 9164.121163764079
  - 9164.121962393703
  - 6516.406122879806
  - 6516.406921509431
  - 6516.4077201390555
  - 6516.408518768681
  - 6516.409317398306
  - 6516.41011602793
  - 6516.410914657555
  - 6516.412511916804
  - 6516.413310546429
  - 6516.414109176054
  - 6516.414907805678
  - 6516.415706435303
  - 6516.416505064927
  - 3868.700665551031
  - 3868.701464180656
  - 3868.7022628102804
  - 3868.703061439905
  - 3868.7038600695296
  - 3868.7046586991546
  - 3868.705457328779
  - 3868.7062559584037
  - 3868.7070545880288
  - 3868.7078532176533
  - 3868.708651847278
  - 3868.7094504769025
  - 3868.7102491065275
  - 1220.9952082222555
  - 1220.99600685188
  - 1220.996805481505
  - 1220.9976041111295
  - 1220.9984027407543
  - 1220.9992013703788
  - 1221.0000000000036
  - 1221.0007986296284
  - 1221.001597259253
  - 1221.0023958888778
  - 1221.0031945185024
  - 1221.0039931481272
  - 1221.0047917777517
  - -1426.7110477361448
  - -1426.7102491065202
  - -1426.7094504768952
  - -1426.7086518472706
  - -1426.707853217646
  - -1426.7070545880215
  - -1426.7062559583965
  - -1426.705457328772
  - -1426.7046586991473
  - -1426.7038600695223
  - -1426.7030614398977
  - -1426.7022628102732
  - -1426.7014641806486
  - -4074.41650506492
  - -4074.4157064352958
  - -4074.4149078056707
  - -4074.4141091760466
  - -4074.4133105464216
  - -4074.4125119167966
  - -4074.4117132871725
  - -4074.4109146575474
  - -4074.4101160279224
  - -4074.4093173982983
  - -4074.4085187686733
  - -4074.4077201390483
  - -4074.406921509424
  - -6722.122761023321
  - -6722.121962393696
  - -6722.121163764072
  - -6722.120365134447
  - -6722.119566504823
  - -6722.118767875198
  - -6722.117170615948
  - -6722.116371986323
  - -6722.115573356698
  - -6722.114774727074
  - -6722.113976097449
  - -6722.113177467824
  - -6722.1123788382
  - -9369.828218352093
  - -9369.827419722467
  - -9369.826621092843
  - -9369.825822463219
  - -9369.825023833593
  - -9369.824225203969
  - -9369.823426574345
  - -9369.822627944719
  - -9369.821829315095
  - -9369.82103068547
  - -9369.820232055845
  - -9369.81943342622
  - -9369.818634796597
  - -12017.534474310498
  - -12017.533675680874
  - -12017.532877051248
  - -12017.532078421624
  - -12017.531279792
  - -12017.530481162374
  - -12017.52968253275
  - -12017.528883903125
  - -12017.5280852735
  - -12017.527286643875
  - -12017.526488014251
  - -12017.525689384625
  - -12017.524890755001
  - -12017.524092125377

  turbine_library_path: ../../turbines
  turbine_type:
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
floris_version: v3.0.0
flow_field:
  air_density: 1.225
  reference_wind_height: -1
  wind_directions:
  - 270.0
  wind_shear: 0.12
  wind_speeds:
  - 8.41
  wind_veer: 0.0
  turbulence_intensities:
  - 0.06
logging:
  console:
    enable: true
    level: WARNING
  file:
    enable: false
    level: WARNING
name: Intermediate FCD Layout Jensen
solver:
  turbine_grid_points: 3
  type: turbine_grid
wake:
  enable_secondary_steering: true
  enable_transverse_velocities: true
  enable_yaw_added_recovery: true
  model_strings:
    combination_model: sosfs
    deflection_model: jimenez
    turbulence_model: crespo_hernandez
    velocity_model: jensen
  wake_deflection_parameters:
    gauss:
      ad: 0.0
      alpha: 0.58
      bd: 0.0
      beta: 0.077
      dm: 1.0
      ka: 0.38
      kb: 0.004
    jimenez:
      ad: 0.0
      bd: 0.0
      kd: 0.05
  wake_turbulence_parameters:
    crespo_hernandez:
      ai: 0.8
      constant: 0.5
      downstream: -0.32
      initial: 0.1
  wake_velocity_parameters:
    cc:
      a_f: 3.11
      a_s: 0.179367259
      alpha_mod: 1.0
      b_f: -0.68
      b_s: 0.0118889215
      c_f: 2.41
      c_s1: 0.0563691592
      c_s2: 0.13290157
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004
    jensen:
      we: 0.05
  enable_active_wake_mixing: false
