description: Standardized Moorings Layout using Jensen-Jimenez
farm:
  layout_x:
  - 9260.909018
  - 7830.968178
  - 6401.027338
  - 4971.086498
  - 3541.145658
  - 2111.204818
  - 681.263978
  - -748.676862
  - -2178.617702
  - -3608.558542
  - -5038.499382
  - -6468.440222
  - -7898.381062
  - -9328.321902
  - 8647.357813
  - 7217.416973
  - 5787.476133
  - 4357.535293
  - 2927.594453
  - 1497.653613
  - 67.712773
  - -1362.228067
  - -2792.168907
  - -4222.109747
  - -5652.050587
  - -7081.991427
  - -8511.932267
  - 9463.747449
  - 8033.806609
  - 6603.865769
  - 5173.924929
  - 3743.984089
  - 2314.043249
  - 884.102409
  - -1975.779271
  - -3405.720111
  - -4835.660951
  - -6265.601791
  - -7695.542631
  - -9125.483471
  - 8850.196244
  - 7420.255404
  - 5990.314564
  - 4560.373724
  - 3130.432884
  - 1700.492044
  - 270.551204
  - -1159.389636
  - -2589.330476
  - -4019.271316
  - -5449.212156
  - -6879.152996
  - -8309.093836
  - 8236.64504
  - 6806.7042
  - 5376.76336
  - 3946.82252
  - 2516.88168
  - 1086.94084
  - -343
  - -1772.94084
  - -3202.88168
  - -4632.82252
  - -6062.76336
  - -7492.7042
  - -8922.64504
  - 9053.034676
  - 7623.093836
  - 6193.152996
  - 4763.212156
  - 3333.271316
  - 1903.330476
  - 473.389636
  - -956.551204
  - -2386.492044
  - -3816.432884
  - -5246.373724
  - -6676.314564
  - -8106.255404
  - 8439.483471
  - 7009.542631
  - 5579.601791
  - 4149.660951
  - 2719.720111
  - 1289.779271
  - -140.161569
  - -1570.102409
  - -3000.043249
  - -4429.984089
  - -5859.924929
  - -7289.865769
  - -8719.806609
  - 9255.873107
  - 7825.932267
  - 6395.991427
  - 4966.050587
  - 3536.109747
  - 2106.168907
  - -753.712773
  - -2183.653613
  - -3613.594453
  - -5043.535293
  - -6473.476133
  - -7903.416973
  - -9333.357813
  - 8642.321902
  - 7212.381062
  - 5782.440222
  - 4352.499382
  - 2922.558542
  - 1492.617702
  - 62.676862
  - -1367.263978
  - -2797.204818
  - -4227.145658
  - -5657.086498
  - -7087.027338
  - -8516.968178
  - 9458.711538
  - 8028.770698
  - 6598.829858
  - 5168.889018
  - 3738.948178
  - 2309.007338
  - 879.066498
  - -550.874342
  - -1980.815182
  - -3410.756022
  - -4840.696862
  - -6270.637702
  - -7700.578542
  - -9130.519382
  layout_y:
  - 11811.817836
  - 11811.818635
  - 11811.819433
  - 11811.820232
  - 11811.821031
  - 11811.821829
  - 11811.822628
  - 11811.823427
  - 11811.824225
  - 11811.825024
  - 11811.825822
  - 11811.826621
  - 11811.82742
  - 11811.828218
  - 9164.112379
  - 9164.113177
  - 9164.113976
  - 9164.114775
  - 9164.115573
  - 9164.116372
  - 9164.117171
  - 9164.117969
  - 9164.118768
  - 9164.119567
  - 9164.120365
  - 9164.121164
  - 9164.121962
  - 6516.406123
  - 6516.406922
  - 6516.40772
  - 6516.408519
  - 6516.409317
  - 6516.410116
  - 6516.410915
  - 6516.412512
  - 6516.413311
  - 6516.414109
  - 6516.414908
  - 6516.415706
  - 6516.416505
  - 3868.700666
  - 3868.701464
  - 3868.702263
  - 3868.703061
  - 3868.70386
  - 3868.704659
  - 3868.705457
  - 3868.706256
  - 3868.707055
  - 3868.707853
  - 3868.708652
  - 3868.70945
  - 3868.710249
  - 1220.995208
  - 1220.996007
  - 1220.996805
  - 1220.997604
  - 1220.998403
  - 1220.999201
  - 1221
  - 1221.000799
  - 1221.001597
  - 1221.002396
  - 1221.003195
  - 1221.003993
  - 1221.004792
  - -1426.711048
  - -1426.710249
  - -1426.70945
  - -1426.708652
  - -1426.707853
  - -1426.707055
  - -1426.706256
  - -1426.705457
  - -1426.704659
  - -1426.70386
  - -1426.703061
  - -1426.702263
  - -1426.701464
  - -4074.416505
  - -4074.415706
  - -4074.414908
  - -4074.414109
  - -4074.413311
  - -4074.412512
  - -4074.411713
  - -4074.410915
  - -4074.410116
  - -4074.409317
  - -4074.408519
  - -4074.40772
  - -4074.406922
  - -6722.122761
  - -6722.121962
  - -6722.121164
  - -6722.120365
  - -6722.119567
  - -6722.118768
  - -6722.117171
  - -6722.116372
  - -6722.115573
  - -6722.114775
  - -6722.113976
  - -6722.113177
  - -6722.112379
  - -9369.828218
  - -9369.82742
  - -9369.826621
  - -9369.825822
  - -9369.825024
  - -9369.824225
  - -9369.823427
  - -9369.822628
  - -9369.821829
  - -9369.821031
  - -9369.820232
  - -9369.819433
  - -9369.818635
  - -12017.534474
  - -12017.533676
  - -12017.532877
  - -12017.532078
  - -12017.53128
  - -12017.530481
  - -12017.529683
  - -12017.528884
  - -12017.528085
  - -12017.527287
  - -12017.526488
  - -12017.525689
  - -12017.524891
  - -12017.524092

  turbine_library_path: ../../turbines
  turbine_type:
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
floris_version: v3.0.0
flow_field:
  air_density: 1.225
  reference_wind_height: -1
  wind_directions:
  - 270.0
  wind_shear: 0.12
  wind_speeds:
  - 8.41
  wind_veer: 0.0
  turbulence_intensities:
  - 0.06
logging:
  console:
    enable: true
    level: WARNING
  file:
    enable: false
    level: WARNING
name: Intermediate FCD Layout Jensen
solver:
  turbine_grid_points: 3
  type: turbine_grid
wake:
  enable_secondary_steering: true
  enable_transverse_velocities: true
  enable_yaw_added_recovery: true
  model_strings:
    combination_model: sosfs
    deflection_model: jimenez
    turbulence_model: crespo_hernandez
    velocity_model: jensen
  wake_deflection_parameters:
    gauss:
      ad: 0.0
      alpha: 0.58
      bd: 0.0
      beta: 0.077
      dm: 1.0
      ka: 0.38
      kb: 0.004
    jimenez:
      ad: 0.0
      bd: 0.0
      kd: 0.05
  wake_turbulence_parameters:
    crespo_hernandez:
      ai: 0.8
      constant: 0.5
      downstream: -0.32
      initial: 0.1
  wake_velocity_parameters:
    cc:
      a_f: 3.11
      a_s: 0.179367259
      alpha_mod: 1.0
      b_f: -0.68
      b_s: 0.0118889215
      c_f: 2.41
      c_s1: 0.0563691592
      c_s2: 0.13290157
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004
    jensen:
      we: 0.05
  enable_active_wake_mixing: false
