description: Standardized Moorings Layout using Jensen-Jimenez
farm:
  layout_x:
  - 8855.07035
  - 8855.126615
  - 8855.182881
  - 8855.239147
  - 8855.295412
  - 8855.351678
  - 8855.407944
  - 8855.464209
  - 8855.520475
  - 8855.576741
  - 8855.633006
  - 8855.689272
  - 8855.745538
  - 6823.704297
  - 6823.760563
  - 6823.816829
  - 6823.873094
  - 6823.92936
  - 6823.985626
  - 6824.041891
  - 6824.098157
  - 6824.154423
  - 6824.210688
  - 6824.266954
  - 6824.32322
  - 6824.379485
  - 6824.435751
  - 4792.394511
  - 4792.450776
  - 4792.507042
  - 4792.563308
  - 4792.619573
  - 4792.675839
  - 4792.732105
  - 4792.78837
  - 4792.844636
  - 4792.900902
  - 4792.957167
  - 4793.013433
  - 4793.069699
  - 2761.084724
  - 2761.14099
  - 2761.197255
  - 2761.253521
  - 2761.309787
  - 2761.366052
  - 2761.422318
  - 2761.478584
  - 2761.534849
  - 2761.591115
  - 2761.647381
  - 2761.703646
  - 2761.759912
  - 729.718672
  - 729.774937
  - 729.831203
  - 729.943734
  - 730
  - 730.056266
  - 730.112531
  - 730.168797
  - 730.225063
  - 730.337594
  - 730.39386
  - 730.450125
  - -1301.591115
  - -1301.534849
  - -1301.478584
  - -1301.422318
  - -1301.366052
  - -1301.309787
  - -1301.253521
  - -1301.197255
  - -1301.14099
  - -1301.084724
  - -1301.028458
  - -1300.972193
  - -1300.915927
  - -3332.957167
  - -3332.900902
  - -3332.844636
  - -3332.78837
  - -3332.732105
  - -3332.675839
  - -3332.619573
  - -3332.563308
  - -3332.507042
  - -3332.450776
  - -3332.394511
  - -3332.338245
  - -3332.281979
  - -3332.225714
  - -5364.266954
  - -5364.210688
  - -5364.154423
  - -5364.098157
  - -5364.041891
  - -5363.985626
  - -5363.92936
  - -5363.873094
  - -5363.816829
  - -5363.760563
  - -5363.704297
  - -5363.648032
  - -5363.591766
  - -7395.576741
  - -7395.520475
  - -7395.464209
  - -7395.407944
  - -7395.351678
  - -7395.295412
  - -7395.239147
  - -7395.182881
  - -7395.126615
  - -7395.07035
  - -7395.014084
  - -7394.957818
  - -7394.901553
  - -9426.942793
  - -9426.886527
  - -9426.830262
  - -9426.773996
  - -9426.71773
  - -9426.661465
  - -9426.605199
  - -9426.548933
  - -9426.492668
  - -9426.436402
  - -9426.380136
  - -9426.323871
  - -9426.267605
  - -9426.211339

  layout_y:
  - -10583.719994
  - -8783.627985
  - -6983.535976
  - -5183.443966
  - -3383.351957
  - -1583.259948
  - 216.832061
  - 2016.92407
  - 3817.016079
  - 5617.108088
  - 7417.200097
  - 9217.292107
  - 11017.384116
  - -11692.951011
  - -9892.859002
  - -8092.766993
  - -6292.674984
  - -4492.582975
  - -2692.490966
  - -892.398957
  - 907.693053
  - 2707.785062
  - 4507.877071
  - 6307.96908
  - 8108.061089
  - 9908.153098
  - 11708.245107
  - -11002.09002
  - -9201.998011
  - -7401.906001
  - -5601.813992
  - -3801.721983
  - -2001.629974
  - -201.537965
  - 1598.554044
  - 3398.646053
  - 5198.738062
  - 6998.830072
  - 8798.922081
  - 10599.01409
  - -10311.229028
  - -8511.137019
  - -6711.04501
  - -4910.953001
  - -3110.860992
  - -1310.768982
  - 489.323027
  - 2289.415036
  - 4089.507045
  - 5889.599054
  - 7689.691063
  - 9489.783072
  - 11289.875081
  - -11420.460046
  - -9620.368036
  - -7820.276027
  - -4220.092009
  - -2420
  - -619.907991
  - 1180.184018
  - 2980.276027
  - 4780.368036
  - 8380.552055
  - 10180.644064
  - 11980.736073
  - -10729.599054
  - -8929.507045
  - -7129.415036
  - -5329.323027
  - -3529.231018
  - -1729.139008
  - 70.953001
  - 1871.04501
  - 3671.137019
  - 5471.229028
  - 7271.321037
  - 9071.413046
  - 10871.505055
  - -11838.830072
  - -10038.738062
  - -8238.646053
  - -6438.554044
  - -4638.462035
  - -2838.370026
  - -1038.278017
  - 761.813992
  - 2561.906001
  - 4361.998011
  - 6162.09002
  - 7962.182029
  - 9762.274038
  - 11562.366047
  - -11147.96908
  - -9347.877071
  - -7547.785062
  - -5747.693053
  - -3947.601043
  - -2147.509034
  - -347.417025
  - 1452.674984
  - 3252.766993
  - 5052.859002
  - 6852.951011
  - 8653.04302
  - 10453.13503
  - -10457.108088
  - -8657.016079
  - -6856.92407
  - -5056.832061
  - -3256.740052
  - -1456.648043
  - 343.443966
  - 2143.535976
  - 3943.627985
  - 5743.719994
  - 7543.812003
  - 9343.904012
  - 11143.996021
  - -11566.339106
  - -9766.247097
  - -7966.155088
  - -6166.063078
  - -4365.971069
  - -2565.87906
  - -765.787051
  - 1034.304958
  - 2834.396967
  - 4634.488976
  - 6434.580985
  - 8234.672995
  - 10034.765004
  - 11834.857013

  turbine_library_path: ../../turbines
  turbine_type:
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
floris_version: v3.0.0
flow_field:
  air_density: 1.225
  reference_wind_height: -1
  wind_directions:
  - 270.0
  wind_shear: 0.12
  wind_speeds:
  - 8.41
  wind_veer: 0.0
  turbulence_intensities:
  - 0.06
logging:
  console:
    enable: true
    level: WARNING
  file:
    enable: false
    level: WARNING
name: Intermediate FCD Layout Jensen
solver:
  turbine_grid_points: 3
  type: turbine_grid
wake:
  enable_secondary_steering: true
  enable_transverse_velocities: true
  enable_yaw_added_recovery: true
  model_strings:
    combination_model: sosfs
    deflection_model: jimenez
    turbulence_model: crespo_hernandez
    velocity_model: jensen
  wake_deflection_parameters:
    gauss:
      ad: 0.0
      alpha: 0.58
      bd: 0.0
      beta: 0.077
      dm: 1.0
      ka: 0.38
      kb: 0.004
    jimenez:
      ad: 0.0
      bd: 0.0
      kd: 0.05
  wake_turbulence_parameters:
    crespo_hernandez:
      ai: 0.8
      constant: 0.5
      downstream: -0.32
      initial: 0.1
  wake_velocity_parameters:
    cc:
      a_f: 3.11
      a_s: 0.179367259
      alpha_mod: 1.0
      b_f: -0.68
      b_s: 0.0118889215
      c_f: 2.41
      c_s1: 0.0563691592
      c_s2: 0.13290157
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004
    jensen:
      we: 0.05
  enable_active_wake_mixing: false
