description: Standardized Moorings Layout using Jensen-Jimenez
farm:
  layout_x:
  - 8591.486618
  - 7309.828152
  - 8833.974628
  - 6028.169685
  - 7552.316161
  - 9076.462637
  - 4746.511219
  - 6270.657695
  - 7794.804171
  - 9318.950647
  - 3464.852752
  - 4988.999228
  - 6513.145704
  - 8037.29218
  - 2183.194285
  - 3707.340761
  - 5231.487238
  - 6755.633714
  - 8279.78019
  - 901.535819
  - 2425.682295
  - 3949.828771
  - 5473.975247
  - 6998.121723
  - 8522.268199
  - -380.122648
  - 1144.023828
  - 2668.170304
  - 4192.31678
  - 5716.463257
  - 7240.609733
  - 8764.756209
  - -1661.781115
  - -137.634639
  - 1386.511838
  - 2910.658314
  - 4434.80479
  - 5958.951266
  - 7483.097742
  - 9007.244218
  - -2943.439581
  - -1419.293105
  - 1628.999847
  - 3153.146323
  - 4677.292799
  - 6201.439275
  - 7725.585752
  - 9249.732228
  - -4225.098048
  - -2700.951572
  - -1176.805096
  - 347.34138
  - 1871.487857
  - 3395.634333
  - 4919.780809
  - 6443.927285
  - 7968.073761
  - -5506.756515
  - -3982.610038
  - -2458.463562
  - -934.317086
  - 589.82939
  - 2113.975866
  - 3638.122342
  - 5162.268818
  - 6686.415294
  - -6788.414981
  - -5264.268505
  - -3740.122029
  - -2215.975553
  - -691.829077
  - 832.317399
  - 2356.463876
  - 3880.610352
  - 5404.756828
  - -8070.073448
  - -6545.926972
  - -5021.780496
  - -3497.634019
  - -1973.487543
  - -449.341067
  - 1074.805409
  - 2598.951885
  - 4123.098361
  - -9351.731914
  - -7827.585438
  - -6303.438962
  - -4779.292486
  - -3255.14601
  - -1730.999534
  - 1317.293418
  - 2841.439895
  - -9109.243905
  - -7585.097429
  - -6060.950953
  - -4536.804477
  - -3012.658
  - -1488.511524
  - 35.634952
  - 1559.781428
  - -8866.755895
  - -7342.609419
  - -5818.462943
  - -4294.316467
  - -2770.169991
  - -1246.023515
  - 278.122961
  - -8624.267886
  - -7100.12141
  - -5575.974934
  - -4051.828458
  - -2527.681981
  - -1003.535505
  - -8381.779876
  - -6857.6334
  - -5333.486924
  - -3809.340448
  - -2285.193972
  - -8139.291867
  - -6615.145391
  - -5090.998915
  - -3566.852439
  - -9420.950334
  - -7896.803858
  - -6372.657381
  - -4848.510905
  - -9178.462324
  - -7654.315848
  - -6130.169372
  - -8935.974315
  - -7411.827839
  - -8693.486305

  layout_y:
  - -11255.729339
  - -11311.522782
  - -8384.582823
  - -11367.316224
  - -8440.376266
  - -5513.436308
  - -11423.109667
  - -8496.169709
  - -5569.22975
  - -2642.289792
  - -11478.903109
  - -8551.963151
  - -5625.023193
  - -2698.083235
  - -11534.696552
  - -8607.756594
  - -5680.816635
  - -2753.876677
  - 173.063281
  - -11590.489994
  - -8663.550036
  - -5736.610078
  - -2809.67012
  - 117.269839
  - 3044.209797
  - -11646.283437
  - -8719.343479
  - -5792.40352
  - -2865.463562
  - 61.476396
  - 2988.416354
  - 5915.356313
  - -11702.07688
  - -8775.136921
  - -5848.196963
  - -2921.257005
  - 5.682954
  - 2932.622912
  - 5859.56287
  - 8786.502828
  - -11757.870322
  - -8830.930364
  - -2977.050447
  - -50.110489
  - 2876.829469
  - 5803.769428
  - 8730.709386
  - 11657.649344
  - -11813.663765
  - -8886.723806
  - -5959.783848
  - -3032.84389
  - -105.903932
  - 2821.036027
  - 5747.975985
  - 8674.915943
  - 11601.855901
  - -11869.457207
  - -8942.517249
  - -6015.577291
  - -3088.637332
  - -161.697374
  - 2765.242584
  - 5692.182542
  - 8619.122501
  - 11546.062459
  - -11925.25065
  - -8998.310691
  - -6071.370733
  - -3144.430775
  - -217.490817
  - 2709.449142
  - 5636.3891
  - 8563.329058
  - 11490.269016
  - -11981.044092
  - -9054.104134
  - -6127.164176
  - -3200.224217
  - -273.284259
  - 2653.655699
  - 5580.595657
  - 8507.535616
  - 11434.475574
  - -12036.837535
  - -9109.897577
  - -6182.957618
  - -3256.01766
  - -329.077702
  - 2597.862256
  - 8451.742173
  - 11378.682131
  - -9165.691019
  - -6238.751061
  - -3311.811103
  - -384.871144
  - 2542.068814
  - 5469.008772
  - 8395.94873
  - 11322.888689
  - -6294.544503
  - -3367.604545
  - -440.664587
  - 2486.275371
  - 5413.21533
  - 8340.155288
  - 11267.095246
  - -3423.397988
  - -496.458029
  - 2430.481929
  - 5357.421887
  - 8284.361845
  - 11211.301804
  - -552.251472
  - 2374.688486
  - 5301.628445
  - 8228.568403
  - 11155.508361
  - 2318.895044
  - 5245.835002
  - 8172.77496
  - 11099.714919
  - 2263.101601
  - 5190.041559
  - 8116.981518
  - 11043.921476
  - 5134.248117
  - 8061.188075
  - 10988.128033
  - 8005.394633
  - 10932.334591
  - 10876.541148

  turbine_library_path: ../../turbines
  turbine_type:
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
floris_version: v3.0.0
flow_field:
  air_density: 1.225
  reference_wind_height: -1
  wind_directions:
  - 270.0
  wind_shear: 0.12
  wind_speeds:
  - 8.41
  wind_veer: 0.0
  turbulence_intensities:
  - 0.06
logging:
  console:
    enable: true
    level: WARNING
  file:
    enable: false
    level: WARNING
name: Intermediate FCD Layout Jensen
solver:
  turbine_grid_points: 3
  type: turbine_grid
wake:
  enable_secondary_steering: true
  enable_transverse_velocities: true
  enable_yaw_added_recovery: true
  model_strings:
    combination_model: sosfs
    deflection_model: jimenez
    turbulence_model: crespo_hernandez
    velocity_model: jensen
  wake_deflection_parameters:
    gauss:
      ad: 0.0
      alpha: 0.58
      bd: 0.0
      beta: 0.077
      dm: 1.0
      ka: 0.38
      kb: 0.004
    jimenez:
      ad: 0.0
      bd: 0.0
      kd: 0.05
  wake_turbulence_parameters:
    crespo_hernandez:
      ai: 0.8
      constant: 0.5
      downstream: -0.32
      initial: 0.1
  wake_velocity_parameters:
    cc:
      a_f: 3.11
      a_s: 0.179367259
      alpha_mod: 1.0
      b_f: -0.68
      b_s: 0.0118889215
      c_f: 2.41
      c_s1: 0.0563691592
      c_s2: 0.13290157
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004
    jensen:
      we: 0.05
  enable_active_wake_mixing: false
