description: Standardized Moorings Layout using Jensen-Jimenez
farm:
  layout_x:
  - -9516.076363
  - -8156.601423
  - -6797.126483
  - -5437.651543
  - -4078.176603
  - -2718.701663
  - -1359.226723
  - 0.248217
  - 1359.723157
  - 2719.198097
  - 4078.673037
  - 5438.147977
  - 6797.622917
  - 8157.097857
  - 9516.572797
  - -9515.984082
  - -8156.509142
  - -6797.034202
  - -5437.559262
  - -4078.084322
  - -2718.609382
  - -1359.134442
  - 0.340498
  - 1359.815438
  - 2719.290378
  - 4078.765318
  - 5438.240258
  - 6797.715198
  - 8157.190138
  - 9516.665078
  - -9515.891801
  - -8156.416861
  - -6796.941921
  - -5437.466981
  - -4077.992041
  - -2718.517101
  - -1359.042161
  - 1359.907719
  - 2719.382659
  - 4078.857599
  - 5438.332539
  - 6797.807479
  - 8157.282419
  - 9516.757359
  - -9515.79952
  - -8156.32458
  - -6796.84964
  - -5437.3747
  - -4077.89976
  - -2718.42482
  - -1358.94988
  - 0.52506
  - 1360
  - 2719.47494
  - 4078.94988
  - 5438.42482
  - 6797.89976
  - 8157.3747
  - 9516.84964
  - -9515.707239
  - -8156.232299
  - -6796.757359
  - -5437.282419
  - -4077.807479
  - -2718.332539
  - -1358.857599
  - 0.617341
  - 1360.092281
  - 2719.567221
  - 4079.042161
  - 5438.517101
  - 6797.992041
  - 8157.466981
  - 9516.941921
  - -9515.614958
  - -8156.140018
  - -6796.665078
  - -5437.190138
  - -4077.715198
  - -2718.240258
  - -1358.765318
  - 0.709622
  - 1360.184562
  - 2719.659502
  - 4079.134442
  - 5438.609382
  - 6798.084322
  - 8157.559262
  - 9517.034202
  - -9515.522677
  - -8156.047737
  - -6796.572797
  - -5437.097857
  - -4077.622917
  - -2718.147977
  - -1358.673037
  - 1360.276843
  - 2719.751783
  - 4079.226723
  - 5438.701663
  - 6798.176603
  - 8157.651543
  - 9517.126483
  - -9515.430396
  - -8155.955456
  - -6796.480516
  - -5437.005576
  - -4077.530636
  - -2718.055696
  - -1358.580756
  - 0.894184
  - 1360.369124
  - 2719.844064
  - 4079.319004
  - 5438.793944
  - 6798.268884
  - 8157.743824
  - 9517.218764
  - -9515.338115
  - -8155.863175
  - -6796.388235
  - -5436.913295
  - -4077.438355
  - -2717.963415
  - -1358.488475
  - 0.986465
  - 1360.461405
  - 2719.936345
  - 4079.411285
  - 5438.886225
  - 6798.361165
  - 8157.836105

  layout_y:
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -11815
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -8918
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -6021
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -3124
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - -227
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 2670
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 5567
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 8464
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361
  - 11361

  turbine_library_path: ../../turbines
  turbine_type:
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
  - iea_15MW_240m
floris_version: v3.0.0
flow_field:
  air_density: 1.225
  reference_wind_height: -1
  wind_directions:
  - 270.0
  wind_shear: 0.12
  wind_speeds:
  - 8.41
  wind_veer: 0.0
  turbulence_intensities:
  - 0.06
logging:
  console:
    enable: true
    level: WARNING
  file:
    enable: false
    level: WARNING
name: Intermediate FCD Layout Jensen
solver:
  turbine_grid_points: 3
  type: turbine_grid
wake:
  enable_secondary_steering: true
  enable_transverse_velocities: true
  enable_yaw_added_recovery: true
  model_strings:
    combination_model: sosfs
    deflection_model: jimenez
    turbulence_model: crespo_hernandez
    velocity_model: jensen
  wake_deflection_parameters:
    gauss:
      ad: 0.0
      alpha: 0.58
      bd: 0.0
      beta: 0.077
      dm: 1.0
      ka: 0.38
      kb: 0.004
    jimenez:
      ad: 0.0
      bd: 0.0
      kd: 0.05
  wake_turbulence_parameters:
    crespo_hernandez:
      ai: 0.8
      constant: 0.5
      downstream: -0.32
      initial: 0.1
  wake_velocity_parameters:
    cc:
      a_f: 3.11
      a_s: 0.179367259
      alpha_mod: 1.0
      b_f: -0.68
      b_s: 0.0118889215
      c_f: 2.41
      c_s1: 0.0563691592
      c_s2: 0.13290157
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004
    jensen:
      we: 0.05
  enable_active_wake_mixing: false
